version: '3'
services:
    gdc-mysql:
        image: mysql:latest
        container_name: gdc-mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_DATABASE=gdc
            - MYSQL_PASSWORD=root
            - MYSQL_PORT=3306
        restart: always
    gdd-mysql:
        image: mysql:latest
        container_name: gdd-mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_DATABASE=gdd
            - MYSQL_PASSWORD=root
            - MYSQL_PORT=3306
        restart: always  
    gdc-activemq:
        image: webcenter/activemq:latest
        container_name: gdc-activemq
        ports:
            - 8161:8161
            - 61616:61616
            - 61613:61613
        environment:
            ACTIVEMQ_NAME: amq
            ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: 'True'
            ACTIVEMQ_ADMIN_LOGIN: admin
            ACTIVEMQ_ADMIN_PASSWORD: admin
    gdc:
        container_name: gdc-docker
        build:
            context: gdc
            dockerfile: DOCKERFILE
        volumes:
            - ./gdc:/gdc
        working_dir: /gdc
        depends_on:
            - gdc-mysql
            - gdc-activemq
        ports:
            - "8888:8080"
        environment:
            - MYSQL_DB_HOST=gdc-mysql
            - MYSQL_DB_PORT=3306
            - MYSQL_DB_USER=root
            - MYSQL_DB_PASS=root
            - GDD_URL=http://gdd-docker:8889/gdc
            - ACTIVEMQ_URL=tcp://gdc-activemq:61616
            - ACTIVEMQ_USER=admin
            - ACTIVEMQ_PASS=admin
        restart: always
    gdd:
        container_name: gdd-docker
        build: 
            context: gdd
            dockerfile: DOCKERFILE
        volumes:
            - ./gdd:/gdd
        working_dir: /gdd
        depends_on:
            - gdd-mysql
        ports:
            - "8889:8080"
        environment:
            - MYSQL_DB_HOST=gdd-mysql
            - MYSQL_DB_PORT=3306
            - MYSQL_DB_USER=root
            - MYSQL_DB_PASS=root
        restart: always